### ISSUE TITLE
Feature: Users can view “Astronomy picture of the day” and its information on a requested date.

### ISSUE THREAD

**Issue by Tiffanytliem** [Tiffanytliem/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view “Astronomy picture of the day” and its information on a requested date.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By default, the current date's "Picture of the day" is shown when is browser is loaded.
User can click on the calendar and select any date, the the page will show the astronomy picture of the selected day.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="633" alt="Ảnh chụp Màn hình 2023-04-25 lúc 23 18 14" src="https://user-images.githubusercontent.com/108093252/234340229-81d711d2-11c2-4c59-82c9-34147228e8bb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Create the HTML file 
- [ ] Add calendar to the HTML page with `<input type="date">` to define a date picker
- [ ] Ensure that the page looks nice on both mobile-sized and desktop-sized screens.
- [ ] Create an AJAX request that pass in the current date as a default argument.
- [ ] Add the info from the AJAX response to the DOM tree. 
- [ ] Listen for `click` event on the `calendar` word to have the calendar showed.
- [ ] Listen for `click` event on the calendar and:
    - [ ] Put the `date` value into a new variable
    - [ ] Update the argument of the AJAX request with the selected date
    - [ ] Add the info from the AJAX response to the DOM tree. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
